name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - uses: actions/checkout@v4

      # Configuración de Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Inicializar el módulo Go (si no se ha hecho previamente)
      - name: Initialize Go module
        run: |
          go mod tidy || true
          go mod vendor || true

      # Compilar el proyecto para Linux
      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o filtop-linux-amd64

      # Ejecutar pruebas (si tienes pruebas)
      - name: Run tests
        run: go test -v ./...
